#server
server:
  port: 8086

# mysql database
spring:
  application:
    name : arine
  datasource:
    url : jdbc:mariadb://localhost:3306/arine
    username : root
    password : 1234
    driver-class-name : org.mariadb.jdbc.Driver
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    check-template-location : true
    cache : false
    
#mybatis:
  #mapper-locations : classpath:mybatis/mapper/*.xml
  #mapper-locations : classpath:mapper/*.xml
  #config-location : classpath:mybatis/mybatis-config.xml